
export const reportsMap = {
    time_to_fill_tile: {
        name: 'TTF Card',
        nameStandard: 'TTF Card',
        nameDayAxis:'TTF Card',
        nameStandardDayAxis: 'TTF Card',
        type: 'report',
        reportPageNumber:1,
        filters:{
            isDisplayTimeFilter:true,
            isDisplayJobTypeFilter:true,
            isDisplayJobCategoryFilter:true,
            isDisplayHiringManagerFilter:true,
            isDisplayRecruiterFilter:true,
            isDisplayJobStatusFilter:true,
            isDisplayDiversityFilter:false,
            isDisplayDeviceFilter:false,
            isDisplayClientFilter:true,
            isDisplayLocationFilter:true
        },
        is_need_tile:false,
        tile_key:''
    },
    time_to_present_tile: {
        name: 'TTP Card',
        nameStandard: 'TTP Card',
        nameDayAxis:'TTP Card',
        nameStandardDayAxis: 'TTP Card',
        type: 'report',
        reportPageNumber:1,
        filters:{
            isDisplayTimeFilter:true,
            isDisplayJobTypeFilter:true,
            isDisplayJobCategoryFilter:true,
            isDisplayHiringManagerFilter:true,
            isDisplayRecruiterFilter:true,
            isDisplayJobStatusFilter:true,
            isDisplayDiversityFilter:false,
            isDisplayDeviceFilter:false,
            isDisplayClientFilter:true,
            isDisplayLocationFilter:true
        },
        is_need_tile:false,
        tile_key:''
    },
    time_to_offer_accept_tile: {
        name: 'TTOA Card',
        nameStandard: 'TTOA Card',
        nameDayAxis:'TTOA Card',
        nameStandardDayAxis: 'TTOA Card',
        type: 'report',
        reportPageNumber:1,
        filters:{
            isDisplayTimeFilter:true,
            isDisplayJobTypeFilter:true,
            isDisplayJobCategoryFilter:true,
            isDisplayHiringManagerFilter:true,
            isDisplayRecruiterFilter:true,
            isDisplayJobStatusFilter:true,
            isDisplayDiversityFilter:false,
            isDisplayDeviceFilter:false,
            isDisplayClientFilter:true,
            isDisplayLocationFilter:true
        },
        is_need_tile:false,
        tile_key:''
    },
    interview_hire_tile: {
        name: 'ITH Card',
        nameStandard: 'ITH Card',
        nameDayAxis:'ITH Card',
        nameStandardDayAxis: 'ITH Card',
        type: 'report',
        reportPageNumber:1,
        filters:{
            isDisplayTimeFilter:true,
            isDisplayJobTypeFilter:true,
            isDisplayJobCategoryFilter:true,
            isDisplayHiringManagerFilter:true,
            isDisplayRecruiterFilter:true,
            isDisplayJobStatusFilter:true,
            isDisplayDiversityFilter:false,
            isDisplayDeviceFilter:false,
            isDisplayClientFilter:true,
            isDisplayLocationFilter:true
        },
        is_need_tile:false,
        tile_key:''
    },
    class_fill_rate_tile: {
        name: 'CFR Card',
        nameStandard: 'CFR Card',
        nameDayAxis:'CFR Card',
        nameStandardDayAxis: 'CFR Card',
        type: 'report',
        reportPageNumber:1,
        filters:{
            isDisplayTimeFilter:true,
            isDisplayJobTypeFilter:true,
            isDisplayJobCategoryFilter:true,
            isDisplayHiringManagerFilter:true,
            isDisplayRecruiterFilter:true,
            isDisplayJobStatusFilter:true,
            isDisplayDiversityFilter:false,
            isDisplayDeviceFilter:false,
            isDisplayClientFilter:true,
            isDisplayLocationFilter:true
        },
        is_need_tile:false,
        tile_key:''
    },
    time_to_fill_report: {
        name: 'TTF Client Config by Month',
        nameStandard: 'TTF Std by Month',
        nameDayAxis:'TTF Client Config by Day',
        nameStandardDayAxis: 'TTF Std by Day',
        type: 'report',
        reportPageNumber:1,
        filters:{
            isDisplayTimeFilter:true,
            isDisplayJobTypeFilter:true,
            isDisplayJobCategoryFilter:true,
            isDisplayHiringManagerFilter:true,
            isDisplayRecruiterFilter:true,
            isDisplayJobStatusFilter:true,
            isDisplayDiversityFilter:false,
            isDisplayDeviceFilter:false,
            isDisplayClientFilter:true,
            isDisplayLocationFilter:true
        },
        is_need_tile:true,
        tile_key:'time_to_fill_tile',
        width:'1245px',
        height:'720px'
    },
    time_to_present_report: {
        name: 'TTP Client Config by Month',
        nameStandard: 'TTP Std by Month',
        nameDayAxis:'TTP Client Config by Day',
        nameStandardDayAxis: 'TTP Std by Day',
        type: 'report',
        reportPageNumber:1,
        filters:{
            isDisplayTimeFilter:true,
            isDisplayJobTypeFilter:true,
            isDisplayJobCategoryFilter:true,
            isDisplayHiringManagerFilter:true,
            isDisplayRecruiterFilter:true,
            isDisplayJobStatusFilter:true,
            isDisplayDiversityFilter:false,
            isDisplayDeviceFilter:false,
            isDisplayClientFilter:true,
            isDisplayLocationFilter:true
        },
        is_need_tile:true,
        tile_key:'time_to_present_tile',
        width:'1245px',
        height:'720px'
    },
    time_to_offer_accept_report: {
        name: 'TTOA Client Config by Month',
        nameStandard: 'TTOA Std by Month',
        nameDayAxis:'TTOA Client Config by Day',
        nameStandardDayAxis: 'TTOA Std by Day',
        type: 'report',
        reportPageNumber:1,
        filters:{
            isDisplayTimeFilter:true,
            isDisplayJobTypeFilter:true,
            isDisplayJobCategoryFilter:true,
            isDisplayHiringManagerFilter:true,
            isDisplayRecruiterFilter:true,
            isDisplayJobStatusFilter:true,
            isDisplayDiversityFilter:false,
            isDisplayDeviceFilter:false,
            isDisplayClientFilter:true,
            isDisplayLocationFilter:true
        },
        is_need_tile:true,
        tile_key:'time_to_offer_accept_tile',
        width:'1245px',
        height:'720px'
    },
    interview_hire_report: {
        name: 'ITH Client Config by Month',
        nameStandard: 'ITH Std by Month',
        nameDayAxis:'ITH Client Config by Day',
        nameStandardDayAxis: 'ITH Std by Day',
        type: 'report',
        reportPageNumber:1,
        filters:{
            isDisplayTimeFilter:true,
            isDisplayJobTypeFilter:true,
            isDisplayJobCategoryFilter:true,
            isDisplayHiringManagerFilter:true,
            isDisplayRecruiterFilter:true,
            isDisplayJobStatusFilter:true,
            isDisplayDiversityFilter:false,
            isDisplayDeviceFilter:false,
            isDisplayClientFilter:true,
            isDisplayLocationFilter:true
        },
        is_need_tile:true,
        tile_key:'interview_hire_tile',
        width:'1245px',
        height:'720px'
    },
    class_fill_rate_report: {
        name: 'CFR Client Config by Month',
        nameStandard: 'CFR Std by Month',
        nameDayAxis:'CFR Client Config by Day',
        nameStandardDayAxis: 'CFR Std by Day',
        type: 'report',
        reportPageNumber:1,
        filters:{
            isDisplayTimeFilter:true,
            isDisplayJobTypeFilter:true,
            isDisplayJobCategoryFilter:true,
            isDisplayHiringManagerFilter:true,
            isDisplayRecruiterFilter:true,
            isDisplayJobStatusFilter:true,
            isDisplayDiversityFilter:false,
            isDisplayDeviceFilter:false,
            isDisplayClientFilter:true,
            isDisplayLocationFilter:true
        },
        is_need_tile:true,
        tile_key:'class_fill_rate_tile',
        width:'1245px',
        height:'720px'
    },
    take_action_report: {
        name: 'Take Action',
        nameStandard: 'Take Action',
        type: 'report',
        reportPageNumber:2,
        filters:{
            isDisplayTimeFilter:false,
            isDisplayJobTypeFilter:true,
            isDisplayJobCategoryFilter:true,
            isDisplayHiringManagerFilter:true,
            isDisplayRecruiterFilter:true,
            isDisplayJobStatusFilter:false,
            isDisplayDiversityFilter:false,
            isDisplayDeviceFilter:false,
            isDisplayClientFilter:true,
            isDisplayLocationFilter:true
        },
        is_need_tile:false,
        tile_key:'',
        width:'1226px',
        height:'787px'
    },
    retrospective_report: {
        name: 'Retrospective',
        nameStandard: 'Retrospective',
        type: 'report',
        reportPageNumber:3,
        filters:{
            isDisplayTimeFilter:true,
            isDisplayJobTypeFilter:true,
            isDisplayJobCategoryFilter:true,
            isDisplayHiringManagerFilter:true,
            isDisplayRecruiterFilter:true,
            isDisplayJobStatusFilter:true,
            isDisplayDiversityFilter:true,
            isDisplayDeviceFilter:false,
            isDisplayClientFilter:true,
            isDisplayLocationFilter:true
        },
        is_need_tile:false,
        tile_key:'',
        width:'1300px',
        height:'1269px'
    },
    recruitment_marketing_report: {
        name: 'Recruitment Marketing',
        nameStandard: 'Recruitment Marketing',
        type: 'report',
        reportPageNumber:4,
        filters:{
            isDisplayTimeFilter:true,
            isDisplayJobTypeFilter:true,
            isDisplayJobCategoryFilter:true,
            isDisplayHiringManagerFilter:false,
            isDisplayRecruiterFilter:false,
            isDisplayJobStatusFilter:true,
            isDisplayDiversityFilter:false,
            isDisplayDeviceFilter:true,
            isDisplayClientFilter:true,
            isDisplayLocationFilter:true
        },
        is_need_tile:false,
        tile_key:'',
        width:'1280px',
        height:'740px'
    },
    campaign_report: {
        name: 'Take Action',
        nameStandard: 'Take Action',
        type: 'report',
        reportPageNumber:2,
        filters:{
            isDisplayTimeFilter:false,
            isDisplayJobTypeFilter:true,
            isDisplayJobCategoryFilter:true,
            isDisplayHiringManagerFilter:true,
            isDisplayRecruiterFilter:true,
            isDisplayJobStatusFilter:false,
            isDisplayDiversityFilter:false,
            isDisplayDeviceFilter:false,
            isDisplayClientFilter:true,
            isDisplayLocationFilter:true
        },
        is_need_tile:false,
        tile_key:'',
        width:'1226px',
        height:'787px'
    },
    mode_median_report: {
        name: 'Take Action',
        nameStandard: 'Take Action',
        type: 'report',
        reportPageNumber:2,
        filters:{
            isDisplayTimeFilter:false,
            isDisplayJobTypeFilter:true,
            isDisplayJobCategoryFilter:true,
            isDisplayHiringManagerFilter:true,
            isDisplayRecruiterFilter:true,
            isDisplayJobStatusFilter:false,
            isDisplayDiversityFilter:false,
            isDisplayDeviceFilter:false,
            isDisplayClientFilter:true,
            isDisplayLocationFilter:true
        },
        is_need_tile:false,
        tile_key:'',
        width:'1226px',
        height:'787px'
    },
    site_statistics_report: {
        name: 'Take Action',
        nameStandard: 'Take Action',
        type: 'report',
        reportPageNumber:2,
        filters:{
            isDisplayTimeFilter:false,
            isDisplayJobTypeFilter:true,
            isDisplayJobCategoryFilter:true,
            isDisplayHiringManagerFilter:true,
            isDisplayRecruiterFilter:true,
            isDisplayJobStatusFilter:false,
            isDisplayDiversityFilter:false,
            isDisplayDeviceFilter:false,
            isDisplayClientFilter:true,
            isDisplayLocationFilter:true
        },
        is_need_tile:false,
        tile_key:'',
        width:'1226px',
        height:'787px'
    }
  };
  export interface ReportFilters {
    isDisplayTimeFilter:boolean,
    isDisplayJobTypeFilter:boolean,
    isDisplayJobCategoryFilter:boolean,
    isDisplayHiringManagerFilter:boolean,
    isDisplayRecruiterFilter:boolean,
    isDisplayJobStatusFilter:boolean,
    isDisplayDiversityFilter:boolean,
    isDisplayDeviceFilter:boolean,
    isDisplayClientFilter:boolean,
    isDisplayLocationFilter:boolean
}